project:
  type: website
  output-dir: docs


resources:
  - Baba.png


website:
  title: "介護過程"
  # 大学名などをフッター（ページ最下部）に入れる場合
  page-footer: 
    left: "©2026 新潟医療福祉大学 社会福祉学科"
    right: "AI 准教授 馬場 監修"
  
  navbar:
    background: "#f8dfe7" # ★ここをピンク（Zoom案内と同じ色）に
    collapse: true
    left:
      - href: index.qmd
        text: はじめに
      - text: "介護課程II"
        menu:
          - href: kaigo_process_201_GH.qmd
            text: "認知症グループホーム"
          - href: kaigo_process_202_SM.qmd
            text: "小規模多機能型居宅介護"
          - href: kaigo_process_203_ICF.qmd
            text: "ICF"
          - href: kaigo_process_204_assessment.qmd
            text: "アセスメント"
          - href: kaigo_process_205_info.qmd
            text: "情報収集（アセスメント）"
          - href: kaigo_process_206_integ.qmd
            text: "統合化（アセスメント）"
          - href: kaigo_process_207_needs.qmd
            text: "生活課題（アセスメント）"
          - href: kaigo_process_208_comm.qmd
            text: "地域密着型サービス"
      - text: "介護課程II（ルビ）"
        menu:
          - href: kaigo_process_201_GH_ruby.qmd
            text: "認知症グループホーム"
          - href: kaigo_process_202_SM_ruby.qmd
            text: "小規模多機能型居宅介護"
          - href: kaigo_process_203_ICF_ruby.qmd
            text: "ICF"
          - href: kaigo_process_204_assessment_ruby.qmd
            text: "アセスメント"
          - href: kaigo_process_205_info_ruby.qmd
            text: "情報収集（アセスメント）"
          - href: kaigo_process_206_integ_ruby.qmd
            text: "統合化（アセスメント）"
          - href: kaigo_process_207_needs_ruby.qmd
            text: "生活課題（アセスメント）"
          - href: kaigo_process_208_comm_ruby.qmd
            text: "地域密着型サービス"
      - text: "初任者研修 1"
        menu:
          - href: sho_101_sho_ruby.qmd
            text: "職務の理解"
          - href: test.qmd
            text: "尊厳の保持・自立支援"
          - href: test.qmd
            text: "介護の基本"
          - href: test.qmd
            text: "介護・福祉サービス"
          - href: test.qmd
            text: "コミュニケーション技術"
          - href: test.qmd
            text: "老化の理解"
          - href: test.qmd
            text: "認知症の理解"
          - href: test.qmd
            text: "障害の理解"
      - text: "初任者研修 2"
        menu:
          - href: test.qmd
            text: "こころ"
          - href: test.qmd
            text: "からだ"
          - href: test.qmd
            text: "生活と家事"
          - href: test.qmd
            text: "快適な居住環境"
          - href: test.qmd
            text: "整容"
          - href: test.qmd
            text: "移動・移乗"
          - href: test.qmd
            text: "食事"
          - href: test.qmd
            text: "入浴・清潔保持"
          - href: test.qmd
            text: "排泄"
          - href: test.qmd
            text: "睡眠"
          - href: test.qmd
            text: "死にゆく人と終末期介護"
      - href: test.qmd
        text: テスト

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: quiz_multi.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/dompurify@3.0.6/dist/purify.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
          <script src="ruby.js"></script>
          <script src="quiz_multi.js"></script>
    include-after-body: header.html

