project:
  type: website
  output-dir: docs


resources:
  - Baba.png


website:
  title: "介護過程"
  # 大学名などをフッター（ページ最下部）に入れる場合
  page-footer: 
    left: "©2026 新潟医療福祉大学 社会福祉学科"
    right: "AI 准教授 馬場 監修"
  
  navbar:
    background: "#f8dfe7" # ★ここをピンク（Zoom案内と同じ色）に
    collapse: true
    left:
      - href: index.qmd
        text: はじめに
      - text: "介護課程II"
        menu:
          - href: kaigo_process_201_GH.qmd
            text: "認知症グループホーム"
          - href: kaigo_process_202_SM.qmd
            text: "小規模多機能型居宅介護"
          - href: kaigo_process_203_ICF.qmd
            text: "ICF"
          - href: kaigo_process_204_assessment.qmd
            text: "アセスメント"
          - href: kaigo_process_205_info.qmd
            text: "情報収集（アセスメント）"
          - href: test.qmd
            text: "統合化（アセスメント）"
          - href: test.qmd
            text: "生活課題（アセスメント）"
          - href: test.qmd
            text: "地域密着型サービス"
      - href: test.qmd
        text: テスト

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: quiz_multi.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/dompurify@3.0.6/dist/purify.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
          <script src="ruby.js"></script>
          <script src="quiz_multi.js"></script>
    include-after-body: header.html

