---
title: "アセスメント"
format:
  html:
    css: styles.css
---

福祉において、アセスメントは介護過程だけではなく様々な場面で行なわれます。
また、介護福祉や社会福祉だけでなく、高齢医学や海外でも行われています。
介護過程は、「アセスメント」「計画立案」「実施」「評価」の 4 つの過程からなるサイクルとされています。
ビジネスなど、福祉以外の分野ではPDCAサイクルと呼ばれるサイクルとほぼ同じです。

介護福祉分野における「アセスメント」は、厚生労働省の提唱する「情報収集」「情報の解釈・関連付け・統合化」に分けられます。テキストによっては、「課題（ニーズ）の明確化」もアセスメントに入ることもあります。それぞれを見ていきましょう・

## 課題分析標準項目

介護実習指導者テキスト改訂２版 p.203

### 基本情報に関する９項目


- 基本情報
- 生活状況
- 利用者の被保険者情報
- 現在利用しているサービスの状況
- 障害老人の日常生活自立度
- 認知症である老人の日常生活自立度
- 主訴
- 認定情報
- 課題分析（アセスメント）理由

### アセスメントに関する１４項目

- 健康状態
- ADL
- IADL
- 認知
- コミュニケーション能力
- 社会との関わり
- 排尿・排便
- 褥瘡・皮膚の問題
- 口腔衛生
- 食事摂取
- 問題行動
- 介護力
- 居住環境
- 特別な状況



## 二つの自立度

介護保険サービスにおいては、二つの自立度があります。
介護の現場では、どちらかを明示せずに会話していることがあります。

[障害高齢者の日常生活自立度（寝たきり度）](https://www.musashino.jrc.or.jp/consult/renkei/_documents/20110520-01-4.pdf) 日本赤十字社

- 生活自立
  - J1: 交通機関等を利用して外出する。
  - J2: 隣近所へなら外出する。
- 準寝たきり
  - A1: 介助により外出し、日中はほとんどベッドから離れて生活する。
  - A2: 外出の頻度が少なく、日中も寝たり起きたりの生活をしている。
- 寝たきり
  - B1: 介助なしで車いすに移乗する。
  - B2: 介助のもと車いすに移乗する。
  - C1: 自力で寝返りできる。
  - C2: 自力では寝返りできない。


[認知症高齢者の日常生活自立度]
(https://www.mhlw.go.jp/topics/2013/02/dl/tp0215-11-11d.pdf)

- I: 何らかの認知症を有するが、日常生活は家庭内及び社会的にはほぼ自立している。
- II: 日常生活に支障をきたすような症状・行動や意思疎通の困難さが多少みられても、誰かが注意していれば自立できる。
  - IIa: 家庭外で上記の状態が見られる。
  - IIb: 家庭内でも上記の状態が見られる。
- III: 日常生活に支障を来すような症状・行動や意志疎通の困難さがときどき見
られ、介護を必要とする。
  - IIIa: 日中を中心として上記の状態が見られる。
  - IIIb: 夜間を中心として上記の状態が見られる。
- IV: 日常生活に支障を来すような症状・行動や意志疎通の困難さが頻繁に見
られ、常に介護を必要とする。
- M: 著しい精神症状や問題行動あるいは重篤な身体疾患が見られ、専門医療
を必要とする。

日常生活自立度で自立度が低いと、要介護判定に影響があります。

認知症高齢者の日常生活自立度 III, IV, M には、加算がつくことがあります。


## 確認テスト

<div id="quiz"></div>

<script>
  window.schoolName = "介護過程";
  window.kakomonName = "アセスメント";
  window.kakomonNChoice = 3;
</script>
<script src="load_gsheet_direct.js"></script>
